[versions]
agp = "8.7.3"
appcompatVersion = "1.3.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
annotationJvm = "1.9.1"
playServicesVision = "20.1.3"

[libraries]
appcompat-v130 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
play-services-vision = { module = "com.google.android.gms:play-services-vision", version.ref = "playServicesVision" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

